controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    cart_effort_controller:
      type: forward_command_controller/ForwardCommandController

cart_effort_controller:
  ros__parameters:
    joints:
      - cart_joint
    interface_name: effort
